-- AlterTable
ALTER TABLE `subscription` MODIFY `subscriptionStatus` ENUM('PENDING_DEPOSIT', 'PENDING_FIRST_SESSION', 'GRACE_PERIOD', 'SUSPENDED', 'ACTIVE', 'CANCELED', 'COMPLETED', 'FULLY_BOOKED') NOT NULL DEFAULT 'PENDING_DEPOSIT';
