allowBuilds:
  '@prisma/engines': false
  argon2: false
  core-js: false
  esbuild: false
  prisma: false
ignoredBuiltDependencies:
  - '@prisma/engines'
  - argon2
  - core-js
  - esbuild
  - prisma
